### ISSUE TITLE
Presence of changelog

### ISSUE THREAD

**Issue by tommens** [WOSPM/checker#43]
I would suggest that the presence of a changelog in some form is also a criterion that tremendously helps in welcoming users or contributors of open source projects. changelogs can of course take many forms, and there are specific guidelines for it, for example:
https://keepachangelog.com/en/1.0.0/ and even automatic changelog generators, for example https://github.com/skywinder/gitlab-changelog-generator

**Comment by umutphp** [comment]
Hi @tommens,

Many thanks for the comment. Let me investigate how checker can check the existence of changelog in the project. 

I think we need to focus the existence first rather than the contents or format of the changelog. What do you think about it?

**Comment by tommens** [comment]
I agree that checking the "existence" of a changelog would be the first step. Even that is not necessarily trivial. There are multiple ways in which the changes in software releases can be reported (some people do not even call it changelog put rather release notes). Some projects use a CHANGELOG file that is updated for every release, others add it as a subsection of the README, others have a dedicated page of their documentation, others use GitHub's "milestones" or "releases" feature, etc.

**Comment by umutphp** [comment]
@tommens 

While doing some investigation, I found a project promoting to create a separate changelog file. [Keep A Changelog](https://keepachangelog.com/en/1.0.0/) describes a format for changelog files.

In FAQ section, they say that;
> What about GitHub Releases?
> 
> It's a great initiative. Releases can be used to turn simple git tags (for example a tag named v1.0.0) into rich release notes by manually adding release notes or it can pull annotated git tag messages and turn them into notes.
> 
> GitHub Releases create a non-portable changelog that can only be displayed to users within the context of GitHub. It's possible to make them look very much like the Keep a Changelog format, but it tends to be a bit more involved.
> 
> The current version of GitHub releases is also arguably not very discoverable by end-users, unlike the typical uppercase files (README, CONTRIBUTING, etc.). Another minor issue is that the interface doesn't currently offer links to commit logs between each release.
> 

I agree with them. Having a separate changelog file )instead of using the release or other tools given by version control system service provide)r could be a good practice.

What do you think about it?

**Comment by tommens** [comment]
To answer your question: I think there are different levels of "good practices". If you talk about projects released through GitHub, I would consider the following levels, personally:
0: The project just has commits, but no explicit tags, nor releases, nor any changelog
1: The project's GitHub repository uses git tags to specific commits to make it easier to find them, but does not use the release feature of GitHub and does not use any changelog either
2: The project's GitHub repository uses both git tags and GitHub releases but no explicit changelog file.
3: In addition to git tags and GitHub releases, the project has a specific changelog file (either a separate file or as integrated in the readme)
4: The changelog file is automatically updated with each new release of the project.

**Comment by umutphp** [comment]
@tommens 
Many thanks for the reply.

As far as I understand from your view, you also agree with me that having a separate changelog file is a good practice. So, we need to create a metric to check the existence of the changelog file and a link from README to the file.

I will create the issue and mention you.

**Comment by umutphp** [comment]
@tommens I created a new metric request #47
