### ISSUE TITLE
WOSPM0024 alternative

### ISSUE THREAD

**Issue by tommens** [WOSPM/checker#46]
**Is your feature request related to a problem? Please describe.**
WOSPM0024 is a good guideline to list contributors, but it is not the only solution. Hence some projects may be welcoming because they provide a list of contributors, but will not be detected as such by the current WOSPM0024.

**Describe the solution you'd like**
Some projects prefer not to list the list of all their contributors as part of the README file (because it might bee too long, or for maintainability reasons). Instead, they may use a separate file to store the list of past and current contributors. This could for example take the form of a file CONTRIBUTORS.md

**Describe alternatives you've considered**
I cannot tell if there is a common standard format or name of such a contributors file, for those cases where it is not part of the readme.

**Comment by umutphp** [comment]
So, the metric should be enhanced to check a link to contributors file too.

For the file name, we can use a list of combinations of "contributors, contributors.md" and upper cases.

**Comment by umutphp** [comment]
Hi @tommens, 

When I check the code, I found that the tool checks the existence of a link to a file or an external resource for the list of contributors. 

I just updated the documentation of the metric.

Many thanks for the issue :).
